### ISSUE TITLE
Doubt over definition of J2000 timestamp

### ISSUE THREAD

**Issue by madhavmk** [uw-ssec/offshore-geodesy#108]
Hello,

I believe that the `gnatss.utilities.time.TimeUnixJ2000` custom class is using the incorrect definition of J2000. As per Wikipedia, J2000.0 epoch is precisely January 1, 2000, noon Terrestrial Time, which is equivalent to January 1, 2000, 11:58:55.816 UTC. 
References: [Wikipedia](https://en.wikipedia.org/wiki/Equinox_(celestial_coordinates)#J2000.0) and [matlab](https://in.mathworks.com/help/matlab/ref/cdflib.breakdowntt2000.html#mw_d9d8c720-28dd-4640-9fdd-307721179f17)
Thus, the class should have either `epoch_scale="tt"` or `epoch_val = "2000-01-01 11:58:55.816"`(keeping `epoch_scale="utc"`).
Please correct me if I am mistaken.

**Comment by lsetiawan** [comment]
Thanks for catching this @madhavmk! I looked into it further, and seems like you are correct! Would you be able to fix this bug? I think the `epoch_scale="tt"` is the way to go. Thank you!

**Comment by madhavmk** [comment]
Hello @lsetiawan, I have updated my PR with this fix. I used `epoch_val = "2000-01-01 11:58:55.816"` keeping `epoch_scale="utc"` because `TimeUnix` format in astropy also defines standard Unix Epoch time relative to UTC.

**Comment by madhavmk** [comment]
Issue fixed with PR [uw-ssec/offshore-geodesy/pull/109](https://github.com/uw-ssec/offshore-geodesy/pull/109)
