### ISSUE TITLE
🚨 Need tests for `loaders` module

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/offshore-geodesy#122]
## Overview

Currently the [`loaders`](https://github.com/uw-ssec/offshore-geodesy/blob/main/src/gnatss/loaders.py) module is at around [22% code coverage](https://app.codecov.io/gh/uw-ssec/offshore-geodesy/blob/main/src%2Fgnatss%2Floaders.py), which means that there are a lot of parts of the code currently untested. Tests are needed for the following functions:

- [x] #123
- [x] #124
- [x] #125
- [x] #126
- [x] #127

**Comment by lsetiawan** [comment]
@madhavmk Please refer to https://github.com/uw-ssec/offshore-geodesy/pull/158 for test data for the loaders.

**Comment by madhavmk** [comment]
Closing this Issue as all sub-tasks are completed.
