### ISSUE TITLE
Finalize package name

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/offshore-geodesy#64]
## Overview

After a conversation with @johnbdesanto regarding the name of the package (seagap). Seems like a finalizing discussion need to be with the community. Once the name is settled references to `seagap` might need to change. The final name need to be established before the initial release of the package as this is critical to how software will appear in docs, modules, package manager, etc.

**Comment by johnbdesanto** [comment]
I just sent an email to the PIs of the seafloor geodetic near-trench experiment. I'm hopeful they can help us reach out to the community and solicit feedback on the package name.
