### ISSUE TITLE
Upgrade the use of pydantic version 1 to 2

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/offshore-geodesy#85]
It would be great to upgrade the use of pydantic version 1 to version 2 since there are a lot of syntax changes. However, let's wait for `autodoc_pydantic` to upgrade first for documentation sake. Looks like lots of progress is being made! See https://github.com/mansenfranzen/autodoc_pydantic/issues/146#issuecomment-1646775697

**Comment by mansenfranzen** [comment]
You can now test the new **autodoc_pydantic** version supporting pydantic v2 via `pip install autodoc_pydantic==2.0.0`. The dev docs already showcase v2 support (see [here](https://autodoc-pydantic.readthedocs.io/en/main-2.x/index.html)). Migration guide is available [here](https://autodoc-pydantic.readthedocs.io/en/main-2.x/users/faq.html#migration-guide-from-v1-to-v2).

Any feedback is more than appreciated. The current **autodoc_pydantic** version `2.0.0` on pypi remains yanked for one week until final release.

**Comment by lsetiawan** [comment]
Thanks @mansenfranzen for letting me know! I really appreciate your hardwork in maintaining the `autodoc_pydantic` library! 🍾
